name: Update Markdown Table

on:
  push:
    paths:
      - 'data.json'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas tabulate
      
    - name: Update README
      run: |
        python .github/scripts/update_readme.py
